In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("pjdata.csv", parse_dates=["계약시작일"])
df

,주택관리번호,공고번호,주택명,주택구분코드,주택구분코드명,주택상세구분코드,주택상세구분코드명,분양구분코드,분양구분코드명,공급지역코드,...,문의처,사업주체명(시행사),입주예정월,투기과열지구,조정대상지역,분양가상한제,정비사업,공공주택지구,대규모택지개발지구,수도권내민영공공주택지구
0,2020000001,2020000001,SH 마곡지구 9단지,1,APT,3,국민,0,분양주택,100,...,1600-3456,서울주택도시공사,202102,Y,Y,Y,N,N,N,N
1,2020000004,2020000004,대구연경A-2블록국민임대,1,APT,3,국민,2,분양전환 불가임대,700,...,1600-1004,한국토지주택대구경북,202005,N,N,N,N,N,N,N
2,2020000005,2020000005,경북도청신도시 코오롱하늘채,1,APT,3,국민,1,분양전환 가능임대,712,...,054-843-1500,경상북도개발공사,202007,N,N,N,N,N,N,N
3,2020000007,2020000007,학성동 동남하이빌아파트,1,APT,1,민영,0,분양주택,680,...,052-268-1866,동남건설산업(주),202003,N,N,N,N,N,N,N
4,2020000008,2020000008,제주첨단과학기술단지A23블록행복주택,1,APT,3,국민,2,분양전환 불가임대,690,...,064-797-5500,제주국제자유도시개발,202008,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1396,2022000601,2022000601,광혜원 포레가,1,APT,1,민영,0,분양주택,360,...,043-534-8181,광혜원지역주택조합,202210,N,N,N,N,N,N,N
1397,2022000602,2022000602,e편한세상 주촌 더프리미어,1,APT,1,민영,0,분양주택,621,...,055-335-1777,주식회사 하나자산신탁,202512,N,N,N,N,N,N,N
1398,2022000612,2022000612,옥천역 금호어울림 더퍼스트,1,APT,1,민영,0,분양주택,360,...,043-731-4992,대한토지신탁(주),202501,N,N,N,N,N,N,N
1399,2022000630,2022000630,장성 바울루체,1,APT,1,민영,0,분양주택,513,...,061-878-8786,한국자산신탁(주),202408,N,N,N,N,N,N,N
1400,2022000640,2022000640,천안 부성지구 우남퍼스트빌,1,APT,1,민영,0,분양주택,312,...,1588-8034,"(주)더블유건설,(주)다림씨앤씨",202403,N,Y,N,N,N,N,N

In [2]:
seoul = df[df['공급위치'].str.contains("서울특별시")]
seoul

,주택관리번호,공고번호,주택명,주택구분코드,주택구분코드명,주택상세구분코드,주택상세구분코드명,분양구분코드,분양구분코드명,공급지역코드,...,문의처,사업주체명(시행사),입주예정월,투기과열지구,조정대상지역,분양가상한제,정비사업,공공주택지구,대규모택지개발지구,수도권내민영공공주택지구
0,2020000001,2020000001,SH 마곡지구 9단지,1,APT,3,국민,0,분양주택,100,...,1600-3456,서울주택도시공사,202102,Y,Y,Y,N,N,N,N
95,2020000312,2020000312,르엘 신반포,1,APT,1,민영,0,분양주택,100,...,1811-8448,롯데건설(주),202212,Y,Y,N,Y,N,N,N
109,2020000338,2020000338,등촌역 한울에이치밸리움,1,APT,1,민영,0,분양주택,100,...,023-661-7008,에이치밸리움,202012,Y,Y,N,N,N,N,N
138,2020000416,2020000416,호반써밋 목동,1,APT,1,민영,0,분양주택,100,...,1566-3382,(주)호반건설,202203,Y,Y,N,Y,N,N,N
185,2020000503,2020000503,우장산숲아이파크,1,APT,1,민영,0,분양주택,100,...,1566-1642,화곡1주택재건축정비사업조합,202211,Y,Y,N,Y,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199,2022000129,2022000129,힐스테이트 세운 센트럴 2단지,1,APT,1,민영,0,분양주택,100,...,02-587-0998,우리자산신탁 주식회사,202302,Y,Y,Y,Y,N,N,N
1254,2022000248,2022000248,창동 다우아트리체 주상복합 아파트,1,APT,1,민영,0,분양주택,100,...,1668-4888,주식회사 하나자산신탁,202502,Y,Y,N,N,N,N,N
1299,2022000364,2022000364,신독산 솔리힐 뉴포레,1,APT,1,민영,0,분양주택,100,...,02-830-2468,동진빌라가로주택정비사업조합,202207,Y,Y,N,N,N,N,N
1350,2022000489,2022000489,천왕역 모아엘가 트레뷰,1,APT,1,민영,0,분양주택,100,...,026-951-1232,주식회사 이레에이치앤씨,202507,Y,Y,N,Y,N,N,N
1378,2022000561,2022000561,남구로역 동일 센타시아,1,APT,1,민영,0,분양주택,100,...,02-876-4004,우리자산신탁 주식회사,202404,Y,Y,N,N,N,N,N

In [3]:
seoul2 = seoul.iloc[:, [10,12,13,26,33,34,35]]
seoul2.sort_values(by="공급위치")

     공급지역명                         공급위치  공급규모      계약시작일 투기과열지구 조정대상지역 분양가상한제
353     서울    서울특별시 강남구 개포1동 660-4번지 일원  1235 2020-08-20      Y      Y      N
290     서울      서울특별시 강남구 개포로 621 (개포동)  2519 2020-11-18      Y      Y      N
339     서울       서울특별시 강남구 대치동 963번지 일원   106 2020-08-31      Y      Y      N
603     서울       서울특별시 강남구 자곡동 335번지 일원   830 2021-04-27      Y      Y      N
604     서울      서울특별시 강남구 자곡동347-5번지 일원   199 2021-04-27      Y      Y      N
...    ...                          ...   ...        ...    ...    ...    ...
1199    서울        서울특별시 중구 입정동 2-4번지 일원   264 2022-05-10      Y      Y      Y
399     서울         서울특별시 중랑구 면목동 55-14    159 2020-08-31      Y      Y      N
582     서울  서울특별시 중랑구 신내동 488-1번지 외 2필지    99 2020-12-28      Y      Y      N
354     서울     서울특별시 중랑구 양원역로 110 (망우동)   134 2020-10-23      N      N      N
610     서울     서울특별시 중랑구 양원역로 110 (망우동)   924 2021-04-14      Y      Y      N

[69 rows x 7 columns]

In [4]:
list = ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구'
        , '도봉구', '동대문구', '동작구', '마포구', 
        '서대문구', '서초구', '성동구', '성북구', '송파구', 
        '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구']

for i in list:
    seoul2['공급위치'][(seoul2['공급위치'].str.contains(i))] = i
    
print(seoul2)

     공급지역명 공급위치  공급규모      계약시작일 투기과열지구 조정대상지역 분양가상한제
0       서울  강서구   962 2020-06-02      Y      Y      Y
95      서울  서초구    67 2020-04-22      Y      Y      N
109     서울  강서구    58 2020-05-11      Y      Y      N
138     서울  양천구   238 2020-05-11      Y      Y      N
185     서울  강서구   242 2020-06-01      Y      Y      N
...    ...  ...   ...        ...    ...    ...    ...
1199    서울   중구   264 2022-05-10      Y      Y      Y
1254    서울  도봉구    89 2022-06-13      Y      Y      N
1299    서울  금천구    35 2022-07-18      Y      Y      N
1350    서울  구로구   140 2022-09-19      Y      Y      N
1378    서울  구로구    91 2022-09-19      Y      Y      N

[69 rows x 7 columns]

C:\Users\rkdgm\AppData\Local\Temp/ipykernel_97296/2345802678.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul2['공급위치'][(seoul2['공급위치'].str.contains(i))] = i
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:8870: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [5]:
import datetime

seoul2["year"] = seoul2["계약시작일"].dt.year
seoul2["month"] = seoul2["계약시작일"].dt.month
seoul2["year_month"] = seoul2['계약시작일'].apply(lambda x:x.strftime('%Y%m'))
x = seoul2.drop(["year","month","계약시작일"], axis = 1)
x

C:\Users\rkdgm\AppData\Local\Temp/ipykernel_97296/912083691.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul2["year"] = seoul2["계약시작일"].dt.year
C:\Users\rkdgm\AppData\Local\Temp/ipykernel_97296/912083691.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul2["month"] = seoul2["계약시작일"].dt.month
C:\Users\rkdgm\AppData\Local\Temp/ipykernel_97296/912083691.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul2["year_month"] = seoul2['계약시작일'].apply(lambda x:x.strftime('%Y%m'))

     공급지역명 공급위치  공급규모 투기과열지구 조정대상지역 분양가상한제 year_month
0       서울  강서구   962      Y      Y      Y     202006
95      서울  서초구    67      Y      Y      N     202004
109     서울  강서구    58      Y      Y      N     202005
138     서울  양천구   238      Y      Y      N     202005
185     서울  강서구   242      Y      Y      N     202006
...    ...  ...   ...    ...    ...    ...        ...
1199    서울   중구   264      Y      Y      Y     202205
1254    서울  도봉구    89      Y      Y      N     202206
1299    서울  금천구    35      Y      Y      N     202207
1350    서울  구로구   140      Y      Y      N     202209
1378    서울  구로구    91      Y      Y      N     202209

[69 rows x 7 columns]

In [6]:
seoul3 = x.rename(columns = {"year_month":"계약시작일"})

In [7]:
seoul3

     공급지역명 공급위치  공급규모 투기과열지구 조정대상지역 분양가상한제   계약시작일
0       서울  강서구   962      Y      Y      Y  202006
95      서울  서초구    67      Y      Y      N  202004
109     서울  강서구    58      Y      Y      N  202005
138     서울  양천구   238      Y      Y      N  202005
185     서울  강서구   242      Y      Y      N  202006
...    ...  ...   ...    ...    ...    ...     ...
1199    서울   중구   264      Y      Y      Y  202205
1254    서울  도봉구    89      Y      Y      N  202206
1299    서울  금천구    35      Y      Y      N  202207
1350    서울  구로구   140      Y      Y      N  202209
1378    서울  구로구    91      Y      Y      N  202209

[69 rows x 7 columns]

In [10]:
x = seoul3.groupby(["공급위치","계약시작일"]).sum()

In [12]:
x.to_csv("공급위치.csv", encoding = 'utf-8-sig')